name: Node CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linting
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - run: npm run lint
     
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [6.x, 8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1

    - name: Start SQLServer
      run: |
        docker pull microsoft/mssql-server-linux
        docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -p 1433:1433 -d microsoft/mssql-server-linux

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up CI configuration
      run: |
        mkdir ~/.tedious
        echo '{
          "config": {
            "server": "localhost",
            "authentication": {
              "type": "default",
              "options": {
                "userName": "sa",
                "password": "yourStrong(!)Password"
              }
            },
            "options": {
              "port": 1433,
              "database": "master"
            }
          }
        }' > ~/.tedious/test-connection.json

    - name: install dependencies
      run: npm install

    - name: run unit tests
      env:
        CODECOV_TOKEN: ${{ secrets. CODECOV_TOKEN }}
      run: npx nyc --reporter=lcov npm run test && npx codecov

    - name: run integration tests (TDS 7.4)
      env:
        TEDIOUS_TDS_VERSION: 7_4
        CODECOV_TOKEN: ${{ secrets. CODECOV_TOKEN }}
      run: npx nyc --reporter=lcov npm run test-integration && npx codecov

    - name: run integration tests (TDS 7.3B)
      env:
        TEDIOUS_TDS_VERSION: 7_3_B
        CODECOV_TOKEN: ${{ secrets. CODECOV_TOKEN }}
      run: npx nyc --reporter=lcov npm run test-integration && npx codecov

    - name: run integration tests (TDS 7.3A)
      env:
        TEDIOUS_TDS_VERSION: 7_3_A
        CODECOV_TOKEN: ${{ secrets. CODECOV_TOKEN }}
      run: npx nyc --reporter=lcov npm run test-integration && npx codecov

    - name: run integration tests (TDS 7.2)
      env:
        TEDIOUS_TDS_VERSION: 7_2
        CODECOV_TOKEN: ${{ secrets. CODECOV_TOKEN }}
      run: npx nyc --reporter=lcov npm run test-integration && npx codecov

    - name: run integration tests (TDS 7.1)
      env:
        TEDIOUS_TDS_VERSION: 7_1
        CODECOV_TOKEN: ${{ secrets. CODECOV_TOKEN }}
      run: npx nyc --reporter=lcov npm run test-integration && npx codecov
